spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cv_reranking?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: 22jiwon
    password: 2Leejiwon!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "cv-reranking-secret-key-cv-reranking-secret-key-123456"
  expiration: 3600000